config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks, shallow: true
  end

  root 'home#index'
  get 'home/index'
  get 'secure_pages/common_dashboard'
  get 'secure_pages/admin_dashboard'
  get 'secure_pages/user_dashboard'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # add default roles for pundit
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.add_role :user
  end

  rolify

  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.  
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/secure_pages_controller.rb
class SecurePagesController < ApplicationController
  before_action :authenticate_user!
  after_action  :verify_authorized

  def user_dashboard
    authorize :secure_page, :user_dashboard?
  end

  def admin_dashboard
    authorize :secure_page, :admin_dashboard?
  end

  def common_dashboard
    authorize :secure_page, :common_dashboard?
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks.all
  end

  def show
    # GET /tasks/1
    # GET /tasks/1.json
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  def edit
    # GET /tasks/1/edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_url(@project), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      # if params[:project_id].present?
      #   @project = Project.find(params[:project_id])
      # else
      #   @project = Task.find(params[:id]).project
      # end
      @project = params.dig(:project_id) ? Project.find(params[:project_id]) : Task.find(params[:id]).project
    end

    def set_task
      # @project = Task.find(params[:id]).project unless @project.present?
      @task = @project.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_flash_type
   return 'alert'  unless flash.alert.nil?
   return 'notice' unless flash.notice.nil?
  end

  def flash_message
    content_tag(:div, class: "\#{get_flash_type} callout text-center") do
      flash.send(get_flash_type)
    end
  end
end  

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
    <h1>You're logged in as: </h1>
    <% if current_user.has_role? :admin %>
      <h3>admin</h3>
    <% end %>

    <% if current_user.has_role? :user %>
        <h3>user</h3>
    <% end %>
<% else %>
    <h1>Welcome to the DemoApp</h1>
    <p>this is the home page of Devise DemoApp</p>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-title">
    <strong>
      <%= link_to Rails.configuration.application_name, root_path %>
    </strong>
  </div>
  <div>
    <div class="top-bar-right">
      
  <ul class="menu align-right">
    <li>
      <%= link_to 'Projects', projects_url  %>
    </li>

    <% if user_signed_in? %>
        <% if current_user.has_role? :user %>
          <li><%= link_to 'user dashboard', secure_pages_user_dashboard_path %>
        <% end %>
        <% if current_user.has_role? :admin %>
          <li><%= link_to 'admin dashboard', secure_pages_admin_dashboard_path %>
        <% end %>
        <li><%= link_to 'common dashboard', secure_pages_common_dashboard_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
  </ul>
    </div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : Rails.configuration.application_name %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <%= render 'layouts/navigation' %>
      <%= flash_message if flash.any? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<h5>
  <%= link_to 'Tasks', project_tasks_url(@project) %>
</h5>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/secure_pages/admin_dashboard.html.erb
<h1>SecurePages#admin_dashboard</h1>
<p>Find me in app/views/secure_pages/admin_dashboard.html.erb</p>

app/views/secure_pages/common_dashboard.html.erb
<p>visible for :user and :admin roles</p>

app/views/secure_pages/user_dashboard.html.erb
<h1>SecurePages#user_dashboard</h1>
<p>Find me in app/views/secure_pages/user_dashboard.html.erb</p>

app/views/tasks/_form.html.erb
<%= form_with(model: task,
              url: (@task.new_record? ? [@project, task] : task_path),
              local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.hidden_field :project_id %>

  <%= form.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', project_tasks_url(@project) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= @project.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', project_tasks_url %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', project_tasks_url(@project) %>